import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import testJpg from "../public/Kazam_screenshot_00006.png";
import { Fragment } from "react";
import { getAllPosts } from "../utils/mdx";

export default function Home({ posts }) {
  return (
    <Fragment>
      <Head>
        <title>Ninja List | Home</title>
      </Head>

      <div>
        <h1>HomePage</h1>
        <p>lorem ipsum dolor sit amet, consectetur adip</p>
        <p>lorem ipsum dolor sit amet, consectetur adip</p>

        <Link href="/ninjas">
          <a>See Ninja Listing</a>
        </Link>

        <div className="wrapper">
          <h1>All Posts</h1>
          <p>
            Click the link below to navigate to a page generated by{" "}
            <code>mdx-bundler</code>.
          </p>
          <ul>
            {posts.map((post, index) => (
              <li key={index}>
                <Link href={`posts/${post.slug}`}>
                  {post.frontmatter.title}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div>
        <Image src={testJpg} alt="test" />
      </div>
    </Fragment>
  );
}

export const getStaticProps = async () => {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
};
